// Copyright 2016 LinkedIn Corp.
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.


/**
 A base class for layouts.
 This layout does not require a view at runtime unless a configuration block has been provided.

 The class is public so that makeView() can conform to the public Layout protocol.
 */
public class BaseLayout<V: View> {

    /// The layout's alignment inside of the rect that it is assigned during arrangement.
    public let alignment: Alignment

    /// The flexibility of the layout along both dimensions.
    public let flexibility: Flexibility

    /// A tag to assign to the view generated by this layout.
    /// A non-zero tag enables the view to be reused.
    public let tag: Int

    /// A configuration block that is run on the main thread after the view is created.
    public let config: (V -> Void)?

    public init(alignment: Alignment, flexibility: Flexibility, tag: Int = 0, config: (V -> Void)?) {
        self.alignment = alignment
        self.flexibility = flexibility
        self.tag = tag
        self.config = config
    }

    public func makeView(from recycler: ViewRecycler, configure: Bool) -> View? {
        guard let config = config else {
            // Nothing needs to be configured, so this layout doesn't require a UIView.
            return nil
        }
        let view: V = recycler.makeView(tag: tag)
        if configure {
            config(view)
        }
        return view
    }
}
